spring.application.name=RESTMongo

#MongoDB configuration
spring.data.mongodb.port=27017
spring.data.mongodb.database=TestDB
### this line must be uncommented if you want to use the app on your host machine
#spring.data.mongodb.host=localhost

### these next lines must be commented if you wish to use the app on your host machine
spring.data.mongodb.host=mongodb
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=aquacloud
spring.data.mongodb.password=aquacloud